#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tkinter as tk

PROGRAM_TITLE = 'Tensorflow Configuration Tool'
TEXTFIELD_WIDTH = 60
TEXTFIELD_PARAMS = ('arial', 10, 'bold')
TEXTFIELD_HEIGHT = 10

class MenuBar(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        tk.Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        self.menubar = tk.Menu(self.parent)
        self.file_menu = tk.Menu(self.menubar, tearoff=0)
        self.menubar.add_cascade(label='File', menu=self.file_menu)
        #self.menubar.add_cascade(label='Edit', menu=self.file_menu)
        #self.menubar.add_cascade(label='View', menu=self.file_menu)
        self.menubar.add_cascade(label='About', menu=self.file_menu)
        self.parent.parent.config(menu=self.menubar)


class LabelSection(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        tk.Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent
        self.config(height = 10)

class Editor(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        tk.Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent
        self.config(pady = 20)

        self.create_textfield()

    def create_textfield(self):
            self.entry = tk.Text(self, width = TEXTFIELD_WIDTH, height = TEXTFIELD_HEIGHT, font = TEXTFIELD_PARAMS)
            self.entry.grid(row = 0, column = 0)


class MainApplication(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        tk.Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        #  menu_bar = tk.Menu(self)
        #  file_menu = tk.Menu(menu_bar, tearoff=0)
        #  menu_bar.add_cascade(label="File", menu=file_menu)
        #  self.parent.config(menu=menu_bar)
        
        # Add menu bar
        self.menubar = MenuBar(self)
        #self.parent.config(menu=self.menubar.menubar)

        # Create GUI elements
        self.labelbar = LabelSection(self)
        self.editor = Editor(self)

        # Place GUI elements
        self.labelbar.grid(row = 0, column = 0)
        self.editor.grid(row=1, column=0)
        #  self.monitor.grid(row = 1, column = 0, columnspan = 3)
        #  self.number_row.grid(row = 3, column = 0)
        #  self.char_block.grid(row = 4, column = 0)
        #  self.spacebar.grid(row = 5, column = 0)
        #  self.arrow_block.grid(row = 4, column = 1, sticky = 'S')
        #  self.number_block.grid(row = 3, column = 2, rowspan = 2)



if __name__ == "__main__":
    root = tk.Tk()
    root.title(PROGRAM_TITLE)
    root.configure(padx = 10, pady = 10)

    #  menu_bar = Menu(self)
    #  file_menu = Menu(menu_bar, tearoff=0)
    #  menu_bar.add_cascade(label="File", menu=file_menu)
    #  .config(menu=menu_bar)

    MainApplication(root).pack(side="top", fill="both", expand=True)
    root.mainloop()
